/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 *
 * split-enforcement-workflow (spec `agents.workflow`): spcb:propose is the
 * FEATURE phase. It creates the proposal, the spec deltas, and the design, and
 * STOPS there — leaving the enforcement/testing sections as TO-BE-FILLED and
 * writing no `enforcement.yaml`. Enforcement is a separate phase completed by
 * /spcb:explore-enforce then /spcb:propose-enforce on the same change.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';
import { STORE_SELECTION_GUIDANCE } from './store-selection.js';
import type { SpecModel } from '../../artifact-graph/types.js';
import { withGovernedGuidance, GOVERNED_AUTHORING_GUIDANCE } from './governed-guidance.js';

/**
 * The feature-phase body shared by the skill and command projections. It drives
 * the agent to produce proposal, specs, and design only, and to leave the
 * enforcement/testing artifacts to the enforcement phase.
 */
const PROPOSE_FEATURE_STEP4 = `4. **Create the feature artifacts in sequence**

   Use the **TodoWrite tool** to track progress through the artifacts.

   Loop through artifacts in dependency order (artifacts with no pending
   dependencies first), stopping once the FEATURE artifacts exist:

   a. **For each artifact that is \`ready\` (dependencies satisfied)**:
      - Get instructions:
        \`\`\`bash
        specbase instructions <artifact-id> --change "<name>" --json
        \`\`\`
      - The instructions JSON includes:
        - \`context\`: Project background (constraints for you - do NOT include in output)
        - \`rules\`: Artifact-specific rules (constraints for you - do NOT include in output)
        - \`template\`: The structure to use for your output file
        - \`instruction\`: Schema-specific guidance for this artifact type
        - \`resolvedOutputPath\`: Resolved path or pattern to write the artifact
        - \`dependencies\`: Completed artifacts to read for context
      - Read any completed dependency files for context
      - Create the artifact file using \`template\` as the structure and write it to \`resolvedOutputPath\`
      - Apply \`context\` and \`rules\` as constraints - but do NOT copy them into the file
      - Show brief progress: "Created <artifact-id>"

   b. **Produce the FEATURE artifacts only**: \`proposal\`, the \`specs\`
      deltas, and \`design\`. Leave the proposal's \`Enforcement intent\` and the
      design's \`Enforcement design\` sections as explicit **TO-BE-FILLED**
      placeholders. **Do NOT write \`enforcement.yaml\`.** Do not create the
      enforcement or evidence tasks yet.

   c. **If an artifact requires user input** (unclear context):
      - Use **AskUserQuestion tool** to clarify
      - Then continue with creation

5. **Show the resting state**
   \`\`\`bash
   specbase status --change "<name>"
   \`\`\`

   The change now rests between phases: features drafted, enforcement pending.
   Enforcement is a separate, deliberate phase - run \`/spcb:explore-enforce\`
   then \`/spcb:propose-enforce\` on the same change to complete it.

**Output**

After producing the feature artifacts, summarize:
- Change name and location
- List of feature artifacts created (proposal, specs, design)
- What's next: "Feature artifacts created. Enforcement is a separate phase:
  run /spcb:explore-enforce then /spcb:propose-enforce."

**Feature-Phase Guardrails**
- Produce proposal, spec deltas, and design only. Do NOT create
  \`enforcement.yaml\` or fill the enforcement/testing sections in this phase.
- Always read dependency artifacts before creating a new one.
- If context is critically unclear, ask the user - but prefer making reasonable
  decisions to keep momentum.
- If a change with that name already exists, ask if user wants to continue it or
  create a new one.
- Verify each artifact file exists after writing before proceeding to next.

The enforcement-quality stance is deliberate: the enforcement judgment happens in
its own phase, after the feature is fixed, so bindings are decided rather than
invented alongside four other artifacts.`;

function featureBody(storeSelection: string): string {
  return `Propose the FEATURE of a new change - create the change and generate the
feature artifacts (proposal, spec deltas, design) in one step. Enforcement is a
separate phase, completed after.

I'll create the feature artifacts:
- proposal.md (what & why)
- specs deltas (what must remain true)
- design.md (how)

Enforcement (enforcement.yaml + testing sections + evidence tasks) is completed
separately by /spcb:propose-enforce after /spcb:explore-enforce. When ready to
run that phase, invoke one of those skills.

---

${storeSelection}

**Input**: The user's request should include a change name (kebab-case) OR a description of what they want to build.

**Steps**

1. **If no clear input provided, ask what they want to build**

   Use the **AskUserQuestion tool** (open-ended, no preset options) to ask:
   > "What change do you want to work on? Describe what you want to build or fix."

   From their description, derive a kebab-case name (e.g., "add user authentication" → \`add-user-auth\`).

   **IMPORTANT**: Do NOT proceed without understanding what the user wants to build.

2. **Create the change directory**
   \`\`\`bash
   specbase new change "<name>"
   \`\`\`
   This creates a scaffolded change in the planning home resolved by the CLI with \`.openspec.yaml\`.

3. **Get the artifact build order**
   \`\`\`bash
   specbase status --change "<name>" --json
   \`\`\`
   Parse the JSON to get:
   - \`applyRequires\`: array of artifact IDs needed before implementation (e.g., \`["tasks"]\`)
   - \`artifacts\`: list of all artifacts with their status and dependencies
   - \`planningHome\`, \`changeRoot\`, \`artifactPaths\`, and \`actionContext\`: path and scope context. Use these instead of assuming repo-local paths.

${PROPOSE_FEATURE_STEP4}`;
}

export function getSpcbProposeSkillTemplate(specModel?: SpecModel): SkillTemplate {
  return {
    name: 'specbase-propose',
    description: 'Propose the FEATURE of a new change: proposal, spec deltas, and design in one step. Enforcement is a separate phase (run /spcb:propose-enforce to complete it). Use when the user wants to describe what they want to build and get the feature artifacts.',
    instructions: withGovernedGuidance(featureBody(STORE_SELECTION_GUIDANCE), specModel, GOVERNED_AUTHORING_GUIDANCE),
    license: 'MIT',
    compatibility: 'Requires specbase CLI.',
    metadata: { author: 'specbase', version: '1.0' },
  };
}

export function getSpcbProposeCommandTemplate(specModel?: SpecModel): CommandTemplate {
  return {
    name: 'SPCB: Propose',
    description: 'Propose the feature of a new change - create proposal, spec deltas, and design in one step; enforcement is a separate phase',
    category: 'Workflow',
    tags: ['workflow', 'artifacts', 'experimental'],
    content: withGovernedGuidance(featureBody(STORE_SELECTION_GUIDANCE), specModel, GOVERNED_AUTHORING_GUIDANCE),
  };
}